# Jekyll Resume Theme

# Site settings
title: Jasleen Kaur Chahal
email: jasleenkaurchahal@gmail.com
description: Jasleen Kaur Chahal's Digital Resume
baseurl: "/"
url: "/"
name: Jasleen Kaur Chahal
job: Computer Science Major
location: Chandigarh, India
languages: HTML, CSS, C, C++, Java and Javascript
twitter_username: jasleenkaurchahal
github_username:  jasleenkaurchahal
email_address: jasleenkaurchahal@gmail.com

# Build settings
markdown: kramdown
